# This rule is not used by the project func-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to functions.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: func-operator
    app.kubernetes.io/managed-by: kustomize
  name: function-viewer-role
rules:
- apiGroups:
  - functions.dev
  resources:
  - functions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - functions.dev
  resources:
  - functions/status
  verbs:
  - get
